version: '3.1'

services:
  library:
    image: 'b2e82b21052b'
    container_name: library
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://database:5432/postgres
    depends_on:
      - database
  database:
    image: 'postgres'
    container_name: database
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres